import type { AIModel } from "./types";

/**
 * Catálogo canônico de modelos suportados pelo Gateway.
 * Custos em créditos internos Dioris — não em USD.
 * Manter alinhado ao Lovable AI Gateway como default backend.
 */
export const AI_MODEL_CATALOG: readonly AIModel[] = [
  {
    id: "google/gemini-3.6-flash",
    provider: "lovable",
    label: "Gemini 3.6 Flash",
    capabilities: ["text", "json", "stream", "tools", "multimodal"],
    quality: "standard",
    speed: "fast",
    cost: "cheap",
    contextTokens: 1_000_000,
    creditsPer1kInput: 1,
    creditsPer1kOutput: 2,
    enabled: true,
  },
  {
    id: "google/gemini-3.1-pro-preview",
    provider: "lovable",
    label: "Gemini 3.1 Pro",
    capabilities: ["text", "json", "stream", "tools", "multimodal"],
    quality: "premium",
    speed: "balanced",
    cost: "balanced",
    contextTokens: 1_000_000,
    creditsPer1kInput: 4,
    creditsPer1kOutput: 8,
    enabled: true,
  },
  {
    id: "openai/gpt-5.4-mini",
    provider: "lovable",
    label: "GPT-5.4 Mini",
    capabilities: ["text", "json", "stream", "tools"],
    quality: "standard",
    speed: "fast",
    cost: "cheap",
    contextTokens: 400_000,
    creditsPer1kInput: 2,
    creditsPer1kOutput: 4,
    enabled: true,
  },
  {
    id: "openai/gpt-5.5",
    provider: "lovable",
    label: "GPT-5.5",
    capabilities: ["text", "json", "stream", "tools"],
    quality: "frontier",
    speed: "slow",
    cost: "premium",
    contextTokens: 400_000,
    creditsPer1kInput: 12,
    creditsPer1kOutput: 24,
    enabled: true,
  },
  {
    id: "google/gemini-embedding-001",
    provider: "lovable",
    label: "Gemini Embedding 001",
    capabilities: ["embedding"],
    quality: "standard",
    speed: "fast",
    cost: "cheap",
    contextTokens: 8_192,
    creditsPer1kInput: 1,
    creditsPer1kOutput: 0,
    enabled: true,
  },
  {
    id: "google/gemini-3-flash-image",
    provider: "lovable",
    label: "Gemini 3 Flash Image",
    capabilities: ["image"],
    quality: "standard",
    speed: "fast",
    cost: "balanced",
    contextTokens: 0,
    creditsPer1kInput: 0,
    creditsPer1kOutput: 0,
    enabled: true,
  },
];
