create extension if not exists pgcrypto;

create table if not exists companies (id uuid primary key default gen_random_uuid(), name text not null, created_at timestamptz not null default now());
create table if not exists products (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id) on delete cascade, name text not null, sku text not null, price_cents integer not null default 0, active boolean not null default true, created_at timestamptz not null default now(), unique(company_id, sku));
create table if not exists inventory (id uuid primary key default gen_random_uuid(), product_id uuid not null references products(id) on delete cascade, quantity integer not null default 0, reserved integer not null default 0, updated_at timestamptz not null default now(), unique(product_id));
create table if not exists sales_channels (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id) on delete cascade, provider text not null, name text not null, status text not null default 'disconnected', created_at timestamptz not null default now());
create table if not exists customers (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id) on delete cascade, name text not null, email text, phone text, created_at timestamptz not null default now());
create table if not exists orders (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id) on delete cascade, channel_id uuid references sales_channels(id) on delete set null, customer_id uuid references customers(id) on delete set null, external_id text, status text not null default 'pending', total_cents integer not null default 0, created_at timestamptz not null default now());
create table if not exists subscription_plans (id uuid primary key default gen_random_uuid(), key text unique not null, name text not null, price_cents integer not null, product_limit integer, channel_limit integer, created_at timestamptz not null default now());
insert into subscription_plans (key, name, price_cents, product_limit, channel_limit) values ('essencial','Essencial',4900,500,1),('profissional','Profissional',12900,null,5),('scale','Scale',29900,null,null) on conflict (key) do nothing;
