/**
 * Fase 3.9 — Preparação de iluminação (HDRI + luzes físicas/IES).
 * Nenhum motor externo. Apenas presets consumíveis por qualquer backend.
 */
import type { RenderHdri, RenderLightPreset } from "../types";

export const RENDER_HDRIS: readonly RenderHdri[] = [
  {
    id: "hdri.studio.soft",
    label: "Estúdio Suave",
    rotation: 0,
    intensity: 1.0,
    temperatureK: 5600,
    category: "estudio",
  },
  {
    id: "hdri.studio.hard",
    label: "Estúdio Dramático",
    rotation: 45,
    intensity: 1.2,
    temperatureK: 5200,
    category: "estudio",
  },
  {
    id: "hdri.interior.day",
    label: "Interior Diurno",
    rotation: 15,
    intensity: 0.9,
    temperatureK: 5400,
    category: "interior",
  },
  {
    id: "hdri.interior.night",
    label: "Interior Noturno",
    rotation: 0,
    intensity: 0.4,
    temperatureK: 3000,
    category: "noturno",
  },
  {
    id: "hdri.exterior.sunny",
    label: "Exterior Ensolarado",
    rotation: 30,
    intensity: 1.5,
    temperatureK: 6200,
    category: "ensolarado",
  },
  {
    id: "hdri.exterior.cloudy",
    label: "Exterior Nublado",
    rotation: 0,
    intensity: 1.0,
    temperatureK: 6800,
    category: "nublado",
  },
  {
    id: "hdri.exterior.sunset",
    label: "Pôr do Sol",
    rotation: 90,
    intensity: 1.3,
    temperatureK: 3200,
    category: "exterior",
  },
  {
    id: "hdri.exterior.blue",
    label: "Golden Blue Hour",
    rotation: 180,
    intensity: 0.8,
    temperatureK: 8000,
    category: "exterior",
  },
];

export const RENDER_LIGHT_PRESETS: readonly RenderLightPreset[] = [
  {
    id: "light.sun.physical",
    kind: "sun",
    label: "Sol Físico",
    intensity: 100000,
    temperatureK: 5600,
    castsShadows: true,
    notes: "Direcional com penumbra angular física.",
  },
  {
    id: "light.ambient.soft",
    kind: "ambient",
    label: "Ambiente Suave",
    intensity: 200,
    temperatureK: 5000,
    castsShadows: false,
  },
  {
    id: "light.area.softbox",
    kind: "area",
    label: "Softbox 60×90",
    intensity: 1200,
    temperatureK: 5600,
    castsShadows: true,
  },
  {
    id: "light.spot.wide",
    kind: "spot",
    label: "Spot Wide 60°",
    intensity: 900,
    temperatureK: 3200,
    castsShadows: true,
  },
  {
    id: "light.spot.narrow",
    kind: "spot",
    label: "Spot Narrow 20°",
    intensity: 1500,
    temperatureK: 3000,
    castsShadows: true,
  },
  {
    id: "light.ies.downlight",
    kind: "ies",
    label: "Downlight IES",
    intensity: 800,
    temperatureK: 3000,
    castsShadows: true,
    iesProfile: "downlight.ies",
  },
  {
    id: "light.ies.wallwasher",
    kind: "ies",
    label: "Wall Washer IES",
    intensity: 700,
    temperatureK: 3500,
    castsShadows: true,
    iesProfile: "wallwash.ies",
  },
  {
    id: "light.led.strip.warm",
    kind: "led",
    label: "Fita LED Quente",
    intensity: 350,
    temperatureK: 2700,
    castsShadows: false,
  },
  {
    id: "light.led.strip.neutral",
    kind: "led",
    label: "Fita LED Neutra",
    intensity: 350,
    temperatureK: 4000,
    castsShadows: false,
  },
  {
    id: "light.profile.linear",
    kind: "profile",
    label: "Perfil Linear",
    intensity: 450,
    temperatureK: 3000,
    castsShadows: false,
  },
  {
    id: "light.pendant.warm",
    kind: "pendant",
    label: "Pendente Decorativo",
    intensity: 500,
    temperatureK: 2700,
    castsShadows: true,
  },
  {
    id: "light.decorative.candle",
    kind: "decorative",
    label: "Vela / Chama",
    intensity: 60,
    temperatureK: 1900,
    castsShadows: false,
  },
  {
    id: "light.hdri",
    kind: "hdri",
    label: "HDRI Ambiente",
    intensity: 1.0,
    temperatureK: 5600,
    castsShadows: true,
  },
];

export const DEFAULT_HDRI_ID = "hdri.interior.day";
