/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTestExternalSupabaseRouteImport } from './routes/api/test-external-supabase'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestExternalSupabaseRoute = ApiTestExternalSupabaseRouteImport.update({
  id: '/api/test-external-supabase',
  path: '/api/test-external-supabase',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/test-external-supabase': typeof ApiTestExternalSupabaseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/test-external-supabase': typeof ApiTestExternalSupabaseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/test-external-supabase': typeof ApiTestExternalSupabaseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/test-external-supabase'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/test-external-supabase'
  id: '__root__' | '/' | '/api/test-external-supabase'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiTestExternalSupabaseRoute: typeof ApiTestExternalSupabaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-external-supabase': {
      id: '/api/test-external-supabase'
      path: '/api/test-external-supabase'
      fullPath: '/api/test-external-supabase'
      preLoaderRoute: typeof ApiTestExternalSupabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiTestExternalSupabaseRoute: ApiTestExternalSupabaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
