/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicTermosRouteImport } from './routes/_public.termos'
import { Route as PublicStatusRouteImport } from './routes/_public.status'
import { Route as PublicSobreRouteImport } from './routes/_public.sobre'
import { Route as PublicSegurancaRouteImport } from './routes/_public.seguranca'
import { Route as PublicReembolsoRouteImport } from './routes/_public.reembolso'
import { Route as PublicRecursosRouteImport } from './routes/_public.recursos'
import { Route as PublicProdutosRouteImport } from './routes/_public.produtos'
import { Route as PublicPrivacidadeRouteImport } from './routes/_public.privacidade'
import { Route as PublicPlanosRouteImport } from './routes/_public.planos'
import { Route as PublicIntegracoesRouteImport } from './routes/_public.integracoes'
import { Route as PublicFaqRouteImport } from './routes/_public.faq'
import { Route as PublicDocsRouteImport } from './routes/_public.docs'
import { Route as PublicCookiesRouteImport } from './routes/_public.cookies'
import { Route as PublicContatoRouteImport } from './routes/_public.contato'
import { Route as PublicChangelogRouteImport } from './routes/_public.changelog'
import { Route as PublicBlogRouteImport } from './routes/_public.blog'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated.workspace'
import { Route as AuthenticatedStorageRouteImport } from './routes/_authenticated.storage'
import { Route as AuthenticatedSitesRouteImport } from './routes/_authenticated.sites'
import { Route as AuthenticatedSistemasRouteImport } from './routes/_authenticated.sistemas'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated.security'
import { Route as AuthenticatedSdkRouteImport } from './routes/_authenticated.sdk'
import { Route as AuthenticatedRecoveryRouteImport } from './routes/_authenticated.recovery'
import { Route as AuthenticatedQualityRouteImport } from './routes/_authenticated.quality'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated.planner'
import { Route as AuthenticatedObservabilidadeRouteImport } from './routes/_authenticated.observabilidade'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated.notificacoes'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated.marketplace'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated.jobs'
import { Route as AuthenticatedIaRouteImport } from './routes/_authenticated.ia'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated.financeiro'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated.crm'
import { Route as AuthenticatedCicdRouteImport } from './routes/_authenticated.cicd'
import { Route as AuthenticatedCacheRouteImport } from './routes/_authenticated.cache'
import { Route as AuthenticatedAutomacaoRouteImport } from './routes/_authenticated.automacao'
import { Route as AuthenticatedApiGatewayRouteImport } from './routes/_authenticated.api-gateway'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedWorkspaceIndexRouteImport } from './routes/_authenticated.workspace.index'
import { Route as AuthenticatedPlannerIndexRouteImport } from './routes/_authenticated.planner.index'
import { Route as AuthenticatedConfiguracoesIndexRouteImport } from './routes/_authenticated.configuracoes.index'
import { Route as PublicProdutosPlannerRouteImport } from './routes/_public.produtos.planner'
import { Route as PublicProdutosCriadorRouteImport } from './routes/_public.produtos.criador'
import { Route as AuthenticatedWorkspacePerfilRouteImport } from './routes/_authenticated.workspace.perfil'
import { Route as AuthenticatedWorkspaceNotificacoesRouteImport } from './routes/_authenticated.workspace.notificacoes'
import { Route as AuthenticatedWorkspaceModulosRouteImport } from './routes/_authenticated.workspace.modulos'
import { Route as AuthenticatedWorkspaceIntegracoesRouteImport } from './routes/_authenticated.workspace.integracoes'
import { Route as AuthenticatedWorkspaceIaRouteImport } from './routes/_authenticated.workspace.ia'
import { Route as AuthenticatedWorkspaceHistoricoRouteImport } from './routes/_authenticated.workspace.historico'
import { Route as AuthenticatedWorkspaceEquipeRouteImport } from './routes/_authenticated.workspace.equipe'
import { Route as AuthenticatedWorkspaceEmpresaRouteImport } from './routes/_authenticated.workspace.empresa'
import { Route as AuthenticatedWorkspaceCreditosRouteImport } from './routes/_authenticated.workspace.creditos'
import { Route as AuthenticatedWorkspaceConfiguracoesRouteImport } from './routes/_authenticated.workspace.configuracoes'
import { Route as AuthenticatedWorkspaceAtividadesRouteImport } from './routes/_authenticated.workspace.atividades'
import { Route as AuthenticatedWorkspaceAssinaturaRouteImport } from './routes/_authenticated.workspace.assinatura'
import { Route as AuthenticatedWorkspaceAssetsRouteImport } from './routes/_authenticated.workspace.assets'
import { Route as AuthenticatedWorkspaceApiKeysRouteImport } from './routes/_authenticated.workspace.api-keys'
import { Route as AuthenticatedWorkspaceAjudaRouteImport } from './routes/_authenticated.workspace.ajuda'
import { Route as AuthenticatedPlannerVisaoRouteImport } from './routes/_authenticated.planner.visao'
import { Route as AuthenticatedPlannerVideoRouteImport } from './routes/_authenticated.planner.video'
import { Route as AuthenticatedPlannerRenderRouteImport } from './routes/_authenticated.planner.render'
import { Route as AuthenticatedPlannerProjetosRouteImport } from './routes/_authenticated.planner.projetos'
import { Route as AuthenticatedPlannerProducaoRouteImport } from './routes/_authenticated.planner.producao'
import { Route as AuthenticatedPlannerOrcamentosRouteImport } from './routes/_authenticated.planner.orcamentos'
import { Route as AuthenticatedPlannerMateriaisRouteImport } from './routes/_authenticated.planner.materiais'
import { Route as AuthenticatedPlannerMarketplaceRouteImport } from './routes/_authenticated.planner.marketplace'
import { Route as AuthenticatedPlannerIaStudioRouteImport } from './routes/_authenticated.planner.ia-studio'
import { Route as AuthenticatedPlannerIaRouteImport } from './routes/_authenticated.planner.ia'
import { Route as AuthenticatedPlannerEngenhariaRouteImport } from './routes/_authenticated.planner.engenharia'
import { Route as AuthenticatedPlannerDecoradoraRouteImport } from './routes/_authenticated.planner.decoradora'
import { Route as AuthenticatedPlannerConfiguradorRouteImport } from './routes/_authenticated.planner.configurador'
import { Route as AuthenticatedPlannerBibliotecaRouteImport } from './routes/_authenticated.planner.biblioteca'
import { Route as AuthenticatedPlannerAssetsRouteImport } from './routes/_authenticated.planner.assets'
import { Route as AuthenticatedConfiguracoesEmpresaRouteImport } from './routes/_authenticated.configuracoes.empresa'
import { Route as AuthenticatedAdminObservabilidadeRouteImport } from './routes/_authenticated.admin.observabilidade'
import { Route as AuthenticatedAdminBillingRouteImport } from './routes/_authenticated.admin.billing'
import { Route as AuthenticatedAdminBibliotecaRouteImport } from './routes/_authenticated.admin.biblioteca'
import { Route as ApiPublicV1StatusRouteImport } from './routes/api/public/v1/status'
import { Route as ApiPublicV1PingRouteImport } from './routes/api/public/v1/ping'
import { Route as ApiPublicV1OpenapiRouteImport } from './routes/api/public/v1/openapi'
import { Route as AuthenticatedPlannerProjetosNovoRouteImport } from './routes/_authenticated.planner.projetos.novo'
import { Route as AuthenticatedPlannerProjetosProjectIdRouteImport } from './routes/_authenticated.planner.projetos.$projectId'
import { Route as ApiPublicV1WorkersRenderRouteImport } from './routes/api/public/v1/workers/render'
import { Route as ApiPublicV1WorkersEmailRouteImport } from './routes/api/public/v1/workers/email'
import { Route as ApiPublicV1WebhooksMercadopagoRouteImport } from './routes/api/public/v1/webhooks/mercadopago'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTermosRoute = PublicTermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => PublicRoute,
} as any)
const PublicStatusRoute = PublicStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSobreRoute = PublicSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSegurancaRoute = PublicSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => PublicRoute,
} as any)
const PublicReembolsoRoute = PublicReembolsoRouteImport.update({
  id: '/reembolso',
  path: '/reembolso',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRecursosRoute = PublicRecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProdutosRoute = PublicProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacidadeRoute = PublicPrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPlanosRoute = PublicPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => PublicRoute,
} as any)
const PublicIntegracoesRoute = PublicIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFaqRoute = PublicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDocsRoute = PublicDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCookiesRoute = PublicCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContatoRoute = PublicContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => PublicRoute,
} as any)
const PublicChangelogRoute = PublicChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogRoute = PublicBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStorageRoute = AuthenticatedStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSitesRoute = AuthenticatedSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSistemasRoute = AuthenticatedSistemasRouteImport.update({
  id: '/sistemas',
  path: '/sistemas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSdkRoute = AuthenticatedSdkRouteImport.update({
  id: '/sdk',
  path: '/sdk',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecoveryRoute = AuthenticatedRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQualityRoute = AuthenticatedQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedObservabilidadeRoute =
  AuthenticatedObservabilidadeRouteImport.update({
    id: '/observabilidade',
    path: '/observabilidade',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIaRoute = AuthenticatedIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCicdRoute = AuthenticatedCicdRouteImport.update({
  id: '/cicd',
  path: '/cicd',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCacheRoute = AuthenticatedCacheRouteImport.update({
  id: '/cache',
  path: '/cache',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAutomacaoRoute = AuthenticatedAutomacaoRouteImport.update({
  id: '/automacao',
  path: '/automacao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApiGatewayRoute = AuthenticatedApiGatewayRouteImport.update({
  id: '/api-gateway',
  path: '/api-gateway',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkspaceIndexRoute =
  AuthenticatedWorkspaceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedPlannerIndexRoute =
  AuthenticatedPlannerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedConfiguracoesIndexRoute =
  AuthenticatedConfiguracoesIndexRouteImport.update({
    id: '/configuracoes/',
    path: '/configuracoes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const PublicProdutosPlannerRoute = PublicProdutosPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => PublicProdutosRoute,
} as any)
const PublicProdutosCriadorRoute = PublicProdutosCriadorRouteImport.update({
  id: '/criador',
  path: '/criador',
  getParentRoute: () => PublicProdutosRoute,
} as any)
const AuthenticatedWorkspacePerfilRoute =
  AuthenticatedWorkspacePerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceNotificacoesRoute =
  AuthenticatedWorkspaceNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceModulosRoute =
  AuthenticatedWorkspaceModulosRouteImport.update({
    id: '/modulos',
    path: '/modulos',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceIntegracoesRoute =
  AuthenticatedWorkspaceIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceIaRoute =
  AuthenticatedWorkspaceIaRouteImport.update({
    id: '/ia',
    path: '/ia',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceHistoricoRoute =
  AuthenticatedWorkspaceHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceEquipeRoute =
  AuthenticatedWorkspaceEquipeRouteImport.update({
    id: '/equipe',
    path: '/equipe',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceEmpresaRoute =
  AuthenticatedWorkspaceEmpresaRouteImport.update({
    id: '/empresa',
    path: '/empresa',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceCreditosRoute =
  AuthenticatedWorkspaceCreditosRouteImport.update({
    id: '/creditos',
    path: '/creditos',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceConfiguracoesRoute =
  AuthenticatedWorkspaceConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceAtividadesRoute =
  AuthenticatedWorkspaceAtividadesRouteImport.update({
    id: '/atividades',
    path: '/atividades',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceAssinaturaRoute =
  AuthenticatedWorkspaceAssinaturaRouteImport.update({
    id: '/assinatura',
    path: '/assinatura',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceAssetsRoute =
  AuthenticatedWorkspaceAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceApiKeysRoute =
  AuthenticatedWorkspaceApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceAjudaRoute =
  AuthenticatedWorkspaceAjudaRouteImport.update({
    id: '/ajuda',
    path: '/ajuda',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedPlannerVisaoRoute =
  AuthenticatedPlannerVisaoRouteImport.update({
    id: '/visao',
    path: '/visao',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedPlannerVideoRoute =
  AuthenticatedPlannerVideoRouteImport.update({
    id: '/video',
    path: '/video',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedPlannerRenderRoute =
  AuthenticatedPlannerRenderRouteImport.update({
    id: '/render',
    path: '/render',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedPlannerProjetosRoute =
  AuthenticatedPlannerProjetosRouteImport.update({
    id: '/projetos',
    path: '/projetos',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedPlannerProducaoRoute =
  AuthenticatedPlannerProducaoRouteImport.update({
    id: '/producao',
    path: '/producao',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedPlannerOrcamentosRoute =
  AuthenticatedPlannerOrcamentosRouteImport.update({
    id: '/orcamentos',
    path: '/orcamentos',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedPlannerMateriaisRoute =
  AuthenticatedPlannerMateriaisRouteImport.update({
    id: '/materiais',
    path: '/materiais',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedPlannerMarketplaceRoute =
  AuthenticatedPlannerMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedPlannerIaStudioRoute =
  AuthenticatedPlannerIaStudioRouteImport.update({
    id: '/ia-studio',
    path: '/ia-studio',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedPlannerIaRoute = AuthenticatedPlannerIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AuthenticatedPlannerRoute,
} as any)
const AuthenticatedPlannerEngenhariaRoute =
  AuthenticatedPlannerEngenhariaRouteImport.update({
    id: '/engenharia',
    path: '/engenharia',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedPlannerDecoradoraRoute =
  AuthenticatedPlannerDecoradoraRouteImport.update({
    id: '/decoradora',
    path: '/decoradora',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedPlannerConfiguradorRoute =
  AuthenticatedPlannerConfiguradorRouteImport.update({
    id: '/configurador',
    path: '/configurador',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedPlannerBibliotecaRoute =
  AuthenticatedPlannerBibliotecaRouteImport.update({
    id: '/biblioteca',
    path: '/biblioteca',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedPlannerAssetsRoute =
  AuthenticatedPlannerAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedConfiguracoesEmpresaRoute =
  AuthenticatedConfiguracoesEmpresaRouteImport.update({
    id: '/configuracoes/empresa',
    path: '/configuracoes/empresa',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminObservabilidadeRoute =
  AuthenticatedAdminObservabilidadeRouteImport.update({
    id: '/observabilidade',
    path: '/observabilidade',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBillingRoute =
  AuthenticatedAdminBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBibliotecaRoute =
  AuthenticatedAdminBibliotecaRouteImport.update({
    id: '/biblioteca',
    path: '/biblioteca',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicV1StatusRoute = ApiPublicV1StatusRouteImport.update({
  id: '/api/public/v1/status',
  path: '/api/public/v1/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1PingRoute = ApiPublicV1PingRouteImport.update({
  id: '/api/public/v1/ping',
  path: '/api/public/v1/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1OpenapiRoute = ApiPublicV1OpenapiRouteImport.update({
  id: '/api/public/v1/openapi',
  path: '/api/public/v1/openapi',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlannerProjetosNovoRoute =
  AuthenticatedPlannerProjetosNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedPlannerProjetosRoute,
  } as any)
const AuthenticatedPlannerProjetosProjectIdRoute =
  AuthenticatedPlannerProjetosProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedPlannerProjetosRoute,
  } as any)
const ApiPublicV1WorkersRenderRoute =
  ApiPublicV1WorkersRenderRouteImport.update({
    id: '/api/public/v1/workers/render',
    path: '/api/public/v1/workers/render',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1WorkersEmailRoute = ApiPublicV1WorkersEmailRouteImport.update({
  id: '/api/public/v1/workers/email',
  path: '/api/public/v1/workers/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1WebhooksMercadopagoRoute =
  ApiPublicV1WebhooksMercadopagoRouteImport.update({
    id: '/api/public/v1/webhooks/mercadopago',
    path: '/api/public/v1/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api-gateway': typeof AuthenticatedApiGatewayRoute
  '/automacao': typeof AuthenticatedAutomacaoRoute
  '/cache': typeof AuthenticatedCacheRoute
  '/cicd': typeof AuthenticatedCicdRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/ia': typeof AuthenticatedIaRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/observabilidade': typeof AuthenticatedObservabilidadeRoute
  '/planner': typeof AuthenticatedPlannerRouteWithChildren
  '/quality': typeof AuthenticatedQualityRoute
  '/recovery': typeof AuthenticatedRecoveryRoute
  '/sdk': typeof AuthenticatedSdkRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/sistemas': typeof AuthenticatedSistemasRoute
  '/sites': typeof AuthenticatedSitesRoute
  '/storage': typeof AuthenticatedStorageRoute
  '/workspace': typeof AuthenticatedWorkspaceRouteWithChildren
  '/blog': typeof PublicBlogRoute
  '/changelog': typeof PublicChangelogRoute
  '/contato': typeof PublicContatoRoute
  '/cookies': typeof PublicCookiesRoute
  '/docs': typeof PublicDocsRoute
  '/faq': typeof PublicFaqRoute
  '/integracoes': typeof PublicIntegracoesRoute
  '/planos': typeof PublicPlanosRoute
  '/privacidade': typeof PublicPrivacidadeRoute
  '/produtos': typeof PublicProdutosRouteWithChildren
  '/recursos': typeof PublicRecursosRoute
  '/reembolso': typeof PublicReembolsoRoute
  '/seguranca': typeof PublicSegurancaRoute
  '/sobre': typeof PublicSobreRoute
  '/status': typeof PublicStatusRoute
  '/termos': typeof PublicTermosRoute
  '/admin/biblioteca': typeof AuthenticatedAdminBibliotecaRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/observabilidade': typeof AuthenticatedAdminObservabilidadeRoute
  '/configuracoes/empresa': typeof AuthenticatedConfiguracoesEmpresaRoute
  '/planner/assets': typeof AuthenticatedPlannerAssetsRoute
  '/planner/biblioteca': typeof AuthenticatedPlannerBibliotecaRoute
  '/planner/configurador': typeof AuthenticatedPlannerConfiguradorRoute
  '/planner/decoradora': typeof AuthenticatedPlannerDecoradoraRoute
  '/planner/engenharia': typeof AuthenticatedPlannerEngenhariaRoute
  '/planner/ia': typeof AuthenticatedPlannerIaRoute
  '/planner/ia-studio': typeof AuthenticatedPlannerIaStudioRoute
  '/planner/marketplace': typeof AuthenticatedPlannerMarketplaceRoute
  '/planner/materiais': typeof AuthenticatedPlannerMateriaisRoute
  '/planner/orcamentos': typeof AuthenticatedPlannerOrcamentosRoute
  '/planner/producao': typeof AuthenticatedPlannerProducaoRoute
  '/planner/projetos': typeof AuthenticatedPlannerProjetosRouteWithChildren
  '/planner/render': typeof AuthenticatedPlannerRenderRoute
  '/planner/video': typeof AuthenticatedPlannerVideoRoute
  '/planner/visao': typeof AuthenticatedPlannerVisaoRoute
  '/workspace/ajuda': typeof AuthenticatedWorkspaceAjudaRoute
  '/workspace/api-keys': typeof AuthenticatedWorkspaceApiKeysRoute
  '/workspace/assets': typeof AuthenticatedWorkspaceAssetsRoute
  '/workspace/assinatura': typeof AuthenticatedWorkspaceAssinaturaRoute
  '/workspace/atividades': typeof AuthenticatedWorkspaceAtividadesRoute
  '/workspace/configuracoes': typeof AuthenticatedWorkspaceConfiguracoesRoute
  '/workspace/creditos': typeof AuthenticatedWorkspaceCreditosRoute
  '/workspace/empresa': typeof AuthenticatedWorkspaceEmpresaRoute
  '/workspace/equipe': typeof AuthenticatedWorkspaceEquipeRoute
  '/workspace/historico': typeof AuthenticatedWorkspaceHistoricoRoute
  '/workspace/ia': typeof AuthenticatedWorkspaceIaRoute
  '/workspace/integracoes': typeof AuthenticatedWorkspaceIntegracoesRoute
  '/workspace/modulos': typeof AuthenticatedWorkspaceModulosRoute
  '/workspace/notificacoes': typeof AuthenticatedWorkspaceNotificacoesRoute
  '/workspace/perfil': typeof AuthenticatedWorkspacePerfilRoute
  '/produtos/criador': typeof PublicProdutosCriadorRoute
  '/produtos/planner': typeof PublicProdutosPlannerRoute
  '/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/planner/': typeof AuthenticatedPlannerIndexRoute
  '/workspace/': typeof AuthenticatedWorkspaceIndexRoute
  '/planner/projetos/$projectId': typeof AuthenticatedPlannerProjetosProjectIdRoute
  '/planner/projetos/novo': typeof AuthenticatedPlannerProjetosNovoRoute
  '/api/public/v1/openapi': typeof ApiPublicV1OpenapiRoute
  '/api/public/v1/ping': typeof ApiPublicV1PingRoute
  '/api/public/v1/status': typeof ApiPublicV1StatusRoute
  '/api/public/v1/webhooks/mercadopago': typeof ApiPublicV1WebhooksMercadopagoRoute
  '/api/public/v1/workers/email': typeof ApiPublicV1WorkersEmailRoute
  '/api/public/v1/workers/render': typeof ApiPublicV1WorkersRenderRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api-gateway': typeof AuthenticatedApiGatewayRoute
  '/automacao': typeof AuthenticatedAutomacaoRoute
  '/cache': typeof AuthenticatedCacheRoute
  '/cicd': typeof AuthenticatedCicdRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/ia': typeof AuthenticatedIaRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/observabilidade': typeof AuthenticatedObservabilidadeRoute
  '/quality': typeof AuthenticatedQualityRoute
  '/recovery': typeof AuthenticatedRecoveryRoute
  '/sdk': typeof AuthenticatedSdkRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/sistemas': typeof AuthenticatedSistemasRoute
  '/sites': typeof AuthenticatedSitesRoute
  '/storage': typeof AuthenticatedStorageRoute
  '/blog': typeof PublicBlogRoute
  '/changelog': typeof PublicChangelogRoute
  '/contato': typeof PublicContatoRoute
  '/cookies': typeof PublicCookiesRoute
  '/docs': typeof PublicDocsRoute
  '/faq': typeof PublicFaqRoute
  '/integracoes': typeof PublicIntegracoesRoute
  '/planos': typeof PublicPlanosRoute
  '/privacidade': typeof PublicPrivacidadeRoute
  '/produtos': typeof PublicProdutosRouteWithChildren
  '/recursos': typeof PublicRecursosRoute
  '/reembolso': typeof PublicReembolsoRoute
  '/seguranca': typeof PublicSegurancaRoute
  '/sobre': typeof PublicSobreRoute
  '/status': typeof PublicStatusRoute
  '/termos': typeof PublicTermosRoute
  '/admin/biblioteca': typeof AuthenticatedAdminBibliotecaRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/observabilidade': typeof AuthenticatedAdminObservabilidadeRoute
  '/configuracoes/empresa': typeof AuthenticatedConfiguracoesEmpresaRoute
  '/planner/assets': typeof AuthenticatedPlannerAssetsRoute
  '/planner/biblioteca': typeof AuthenticatedPlannerBibliotecaRoute
  '/planner/configurador': typeof AuthenticatedPlannerConfiguradorRoute
  '/planner/decoradora': typeof AuthenticatedPlannerDecoradoraRoute
  '/planner/engenharia': typeof AuthenticatedPlannerEngenhariaRoute
  '/planner/ia': typeof AuthenticatedPlannerIaRoute
  '/planner/ia-studio': typeof AuthenticatedPlannerIaStudioRoute
  '/planner/marketplace': typeof AuthenticatedPlannerMarketplaceRoute
  '/planner/materiais': typeof AuthenticatedPlannerMateriaisRoute
  '/planner/orcamentos': typeof AuthenticatedPlannerOrcamentosRoute
  '/planner/producao': typeof AuthenticatedPlannerProducaoRoute
  '/planner/projetos': typeof AuthenticatedPlannerProjetosRouteWithChildren
  '/planner/render': typeof AuthenticatedPlannerRenderRoute
  '/planner/video': typeof AuthenticatedPlannerVideoRoute
  '/planner/visao': typeof AuthenticatedPlannerVisaoRoute
  '/workspace/ajuda': typeof AuthenticatedWorkspaceAjudaRoute
  '/workspace/api-keys': typeof AuthenticatedWorkspaceApiKeysRoute
  '/workspace/assets': typeof AuthenticatedWorkspaceAssetsRoute
  '/workspace/assinatura': typeof AuthenticatedWorkspaceAssinaturaRoute
  '/workspace/atividades': typeof AuthenticatedWorkspaceAtividadesRoute
  '/workspace/configuracoes': typeof AuthenticatedWorkspaceConfiguracoesRoute
  '/workspace/creditos': typeof AuthenticatedWorkspaceCreditosRoute
  '/workspace/empresa': typeof AuthenticatedWorkspaceEmpresaRoute
  '/workspace/equipe': typeof AuthenticatedWorkspaceEquipeRoute
  '/workspace/historico': typeof AuthenticatedWorkspaceHistoricoRoute
  '/workspace/ia': typeof AuthenticatedWorkspaceIaRoute
  '/workspace/integracoes': typeof AuthenticatedWorkspaceIntegracoesRoute
  '/workspace/modulos': typeof AuthenticatedWorkspaceModulosRoute
  '/workspace/notificacoes': typeof AuthenticatedWorkspaceNotificacoesRoute
  '/workspace/perfil': typeof AuthenticatedWorkspacePerfilRoute
  '/produtos/criador': typeof PublicProdutosCriadorRoute
  '/produtos/planner': typeof PublicProdutosPlannerRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesIndexRoute
  '/planner': typeof AuthenticatedPlannerIndexRoute
  '/workspace': typeof AuthenticatedWorkspaceIndexRoute
  '/planner/projetos/$projectId': typeof AuthenticatedPlannerProjetosProjectIdRoute
  '/planner/projetos/novo': typeof AuthenticatedPlannerProjetosNovoRoute
  '/api/public/v1/openapi': typeof ApiPublicV1OpenapiRoute
  '/api/public/v1/ping': typeof ApiPublicV1PingRoute
  '/api/public/v1/status': typeof ApiPublicV1StatusRoute
  '/api/public/v1/webhooks/mercadopago': typeof ApiPublicV1WebhooksMercadopagoRoute
  '/api/public/v1/workers/email': typeof ApiPublicV1WorkersEmailRoute
  '/api/public/v1/workers/render': typeof ApiPublicV1WorkersRenderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/api-gateway': typeof AuthenticatedApiGatewayRoute
  '/_authenticated/automacao': typeof AuthenticatedAutomacaoRoute
  '/_authenticated/cache': typeof AuthenticatedCacheRoute
  '/_authenticated/cicd': typeof AuthenticatedCicdRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/ia': typeof AuthenticatedIaRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/observabilidade': typeof AuthenticatedObservabilidadeRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRouteWithChildren
  '/_authenticated/quality': typeof AuthenticatedQualityRoute
  '/_authenticated/recovery': typeof AuthenticatedRecoveryRoute
  '/_authenticated/sdk': typeof AuthenticatedSdkRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/sistemas': typeof AuthenticatedSistemasRoute
  '/_authenticated/sites': typeof AuthenticatedSitesRoute
  '/_authenticated/storage': typeof AuthenticatedStorageRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRouteWithChildren
  '/_public/blog': typeof PublicBlogRoute
  '/_public/changelog': typeof PublicChangelogRoute
  '/_public/contato': typeof PublicContatoRoute
  '/_public/cookies': typeof PublicCookiesRoute
  '/_public/docs': typeof PublicDocsRoute
  '/_public/faq': typeof PublicFaqRoute
  '/_public/integracoes': typeof PublicIntegracoesRoute
  '/_public/planos': typeof PublicPlanosRoute
  '/_public/privacidade': typeof PublicPrivacidadeRoute
  '/_public/produtos': typeof PublicProdutosRouteWithChildren
  '/_public/recursos': typeof PublicRecursosRoute
  '/_public/reembolso': typeof PublicReembolsoRoute
  '/_public/seguranca': typeof PublicSegurancaRoute
  '/_public/sobre': typeof PublicSobreRoute
  '/_public/status': typeof PublicStatusRoute
  '/_public/termos': typeof PublicTermosRoute
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/admin/biblioteca': typeof AuthenticatedAdminBibliotecaRoute
  '/_authenticated/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/_authenticated/admin/observabilidade': typeof AuthenticatedAdminObservabilidadeRoute
  '/_authenticated/configuracoes/empresa': typeof AuthenticatedConfiguracoesEmpresaRoute
  '/_authenticated/planner/assets': typeof AuthenticatedPlannerAssetsRoute
  '/_authenticated/planner/biblioteca': typeof AuthenticatedPlannerBibliotecaRoute
  '/_authenticated/planner/configurador': typeof AuthenticatedPlannerConfiguradorRoute
  '/_authenticated/planner/decoradora': typeof AuthenticatedPlannerDecoradoraRoute
  '/_authenticated/planner/engenharia': typeof AuthenticatedPlannerEngenhariaRoute
  '/_authenticated/planner/ia': typeof AuthenticatedPlannerIaRoute
  '/_authenticated/planner/ia-studio': typeof AuthenticatedPlannerIaStudioRoute
  '/_authenticated/planner/marketplace': typeof AuthenticatedPlannerMarketplaceRoute
  '/_authenticated/planner/materiais': typeof AuthenticatedPlannerMateriaisRoute
  '/_authenticated/planner/orcamentos': typeof AuthenticatedPlannerOrcamentosRoute
  '/_authenticated/planner/producao': typeof AuthenticatedPlannerProducaoRoute
  '/_authenticated/planner/projetos': typeof AuthenticatedPlannerProjetosRouteWithChildren
  '/_authenticated/planner/render': typeof AuthenticatedPlannerRenderRoute
  '/_authenticated/planner/video': typeof AuthenticatedPlannerVideoRoute
  '/_authenticated/planner/visao': typeof AuthenticatedPlannerVisaoRoute
  '/_authenticated/workspace/ajuda': typeof AuthenticatedWorkspaceAjudaRoute
  '/_authenticated/workspace/api-keys': typeof AuthenticatedWorkspaceApiKeysRoute
  '/_authenticated/workspace/assets': typeof AuthenticatedWorkspaceAssetsRoute
  '/_authenticated/workspace/assinatura': typeof AuthenticatedWorkspaceAssinaturaRoute
  '/_authenticated/workspace/atividades': typeof AuthenticatedWorkspaceAtividadesRoute
  '/_authenticated/workspace/configuracoes': typeof AuthenticatedWorkspaceConfiguracoesRoute
  '/_authenticated/workspace/creditos': typeof AuthenticatedWorkspaceCreditosRoute
  '/_authenticated/workspace/empresa': typeof AuthenticatedWorkspaceEmpresaRoute
  '/_authenticated/workspace/equipe': typeof AuthenticatedWorkspaceEquipeRoute
  '/_authenticated/workspace/historico': typeof AuthenticatedWorkspaceHistoricoRoute
  '/_authenticated/workspace/ia': typeof AuthenticatedWorkspaceIaRoute
  '/_authenticated/workspace/integracoes': typeof AuthenticatedWorkspaceIntegracoesRoute
  '/_authenticated/workspace/modulos': typeof AuthenticatedWorkspaceModulosRoute
  '/_authenticated/workspace/notificacoes': typeof AuthenticatedWorkspaceNotificacoesRoute
  '/_authenticated/workspace/perfil': typeof AuthenticatedWorkspacePerfilRoute
  '/_public/produtos/criador': typeof PublicProdutosCriadorRoute
  '/_public/produtos/planner': typeof PublicProdutosPlannerRoute
  '/_authenticated/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/_authenticated/planner/': typeof AuthenticatedPlannerIndexRoute
  '/_authenticated/workspace/': typeof AuthenticatedWorkspaceIndexRoute
  '/_authenticated/planner/projetos/$projectId': typeof AuthenticatedPlannerProjetosProjectIdRoute
  '/_authenticated/planner/projetos/novo': typeof AuthenticatedPlannerProjetosNovoRoute
  '/api/public/v1/openapi': typeof ApiPublicV1OpenapiRoute
  '/api/public/v1/ping': typeof ApiPublicV1PingRoute
  '/api/public/v1/status': typeof ApiPublicV1StatusRoute
  '/api/public/v1/webhooks/mercadopago': typeof ApiPublicV1WebhooksMercadopagoRoute
  '/api/public/v1/workers/email': typeof ApiPublicV1WorkersEmailRoute
  '/api/public/v1/workers/render': typeof ApiPublicV1WorkersRenderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/api-gateway'
    | '/automacao'
    | '/cache'
    | '/cicd'
    | '/crm'
    | '/financeiro'
    | '/ia'
    | '/jobs'
    | '/marketplace'
    | '/notificacoes'
    | '/observabilidade'
    | '/planner'
    | '/quality'
    | '/recovery'
    | '/sdk'
    | '/security'
    | '/sistemas'
    | '/sites'
    | '/storage'
    | '/workspace'
    | '/blog'
    | '/changelog'
    | '/contato'
    | '/cookies'
    | '/docs'
    | '/faq'
    | '/integracoes'
    | '/planos'
    | '/privacidade'
    | '/produtos'
    | '/recursos'
    | '/reembolso'
    | '/seguranca'
    | '/sobre'
    | '/status'
    | '/termos'
    | '/admin/biblioteca'
    | '/admin/billing'
    | '/admin/observabilidade'
    | '/configuracoes/empresa'
    | '/planner/assets'
    | '/planner/biblioteca'
    | '/planner/configurador'
    | '/planner/decoradora'
    | '/planner/engenharia'
    | '/planner/ia'
    | '/planner/ia-studio'
    | '/planner/marketplace'
    | '/planner/materiais'
    | '/planner/orcamentos'
    | '/planner/producao'
    | '/planner/projetos'
    | '/planner/render'
    | '/planner/video'
    | '/planner/visao'
    | '/workspace/ajuda'
    | '/workspace/api-keys'
    | '/workspace/assets'
    | '/workspace/assinatura'
    | '/workspace/atividades'
    | '/workspace/configuracoes'
    | '/workspace/creditos'
    | '/workspace/empresa'
    | '/workspace/equipe'
    | '/workspace/historico'
    | '/workspace/ia'
    | '/workspace/integracoes'
    | '/workspace/modulos'
    | '/workspace/notificacoes'
    | '/workspace/perfil'
    | '/produtos/criador'
    | '/produtos/planner'
    | '/configuracoes/'
    | '/planner/'
    | '/workspace/'
    | '/planner/projetos/$projectId'
    | '/planner/projetos/novo'
    | '/api/public/v1/openapi'
    | '/api/public/v1/ping'
    | '/api/public/v1/status'
    | '/api/public/v1/webhooks/mercadopago'
    | '/api/public/v1/workers/email'
    | '/api/public/v1/workers/render'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/api-gateway'
    | '/automacao'
    | '/cache'
    | '/cicd'
    | '/crm'
    | '/financeiro'
    | '/ia'
    | '/jobs'
    | '/marketplace'
    | '/notificacoes'
    | '/observabilidade'
    | '/quality'
    | '/recovery'
    | '/sdk'
    | '/security'
    | '/sistemas'
    | '/sites'
    | '/storage'
    | '/blog'
    | '/changelog'
    | '/contato'
    | '/cookies'
    | '/docs'
    | '/faq'
    | '/integracoes'
    | '/planos'
    | '/privacidade'
    | '/produtos'
    | '/recursos'
    | '/reembolso'
    | '/seguranca'
    | '/sobre'
    | '/status'
    | '/termos'
    | '/admin/biblioteca'
    | '/admin/billing'
    | '/admin/observabilidade'
    | '/configuracoes/empresa'
    | '/planner/assets'
    | '/planner/biblioteca'
    | '/planner/configurador'
    | '/planner/decoradora'
    | '/planner/engenharia'
    | '/planner/ia'
    | '/planner/ia-studio'
    | '/planner/marketplace'
    | '/planner/materiais'
    | '/planner/orcamentos'
    | '/planner/producao'
    | '/planner/projetos'
    | '/planner/render'
    | '/planner/video'
    | '/planner/visao'
    | '/workspace/ajuda'
    | '/workspace/api-keys'
    | '/workspace/assets'
    | '/workspace/assinatura'
    | '/workspace/atividades'
    | '/workspace/configuracoes'
    | '/workspace/creditos'
    | '/workspace/empresa'
    | '/workspace/equipe'
    | '/workspace/historico'
    | '/workspace/ia'
    | '/workspace/integracoes'
    | '/workspace/modulos'
    | '/workspace/notificacoes'
    | '/workspace/perfil'
    | '/produtos/criador'
    | '/produtos/planner'
    | '/configuracoes'
    | '/planner'
    | '/workspace'
    | '/planner/projetos/$projectId'
    | '/planner/projetos/novo'
    | '/api/public/v1/openapi'
    | '/api/public/v1/ping'
    | '/api/public/v1/status'
    | '/api/public/v1/webhooks/mercadopago'
    | '/api/public/v1/workers/email'
    | '/api/public/v1/workers/render'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/api-gateway'
    | '/_authenticated/automacao'
    | '/_authenticated/cache'
    | '/_authenticated/cicd'
    | '/_authenticated/crm'
    | '/_authenticated/financeiro'
    | '/_authenticated/ia'
    | '/_authenticated/jobs'
    | '/_authenticated/marketplace'
    | '/_authenticated/notificacoes'
    | '/_authenticated/observabilidade'
    | '/_authenticated/planner'
    | '/_authenticated/quality'
    | '/_authenticated/recovery'
    | '/_authenticated/sdk'
    | '/_authenticated/security'
    | '/_authenticated/sistemas'
    | '/_authenticated/sites'
    | '/_authenticated/storage'
    | '/_authenticated/workspace'
    | '/_public/blog'
    | '/_public/changelog'
    | '/_public/contato'
    | '/_public/cookies'
    | '/_public/docs'
    | '/_public/faq'
    | '/_public/integracoes'
    | '/_public/planos'
    | '/_public/privacidade'
    | '/_public/produtos'
    | '/_public/recursos'
    | '/_public/reembolso'
    | '/_public/seguranca'
    | '/_public/sobre'
    | '/_public/status'
    | '/_public/termos'
    | '/_public/'
    | '/_authenticated/admin/biblioteca'
    | '/_authenticated/admin/billing'
    | '/_authenticated/admin/observabilidade'
    | '/_authenticated/configuracoes/empresa'
    | '/_authenticated/planner/assets'
    | '/_authenticated/planner/biblioteca'
    | '/_authenticated/planner/configurador'
    | '/_authenticated/planner/decoradora'
    | '/_authenticated/planner/engenharia'
    | '/_authenticated/planner/ia'
    | '/_authenticated/planner/ia-studio'
    | '/_authenticated/planner/marketplace'
    | '/_authenticated/planner/materiais'
    | '/_authenticated/planner/orcamentos'
    | '/_authenticated/planner/producao'
    | '/_authenticated/planner/projetos'
    | '/_authenticated/planner/render'
    | '/_authenticated/planner/video'
    | '/_authenticated/planner/visao'
    | '/_authenticated/workspace/ajuda'
    | '/_authenticated/workspace/api-keys'
    | '/_authenticated/workspace/assets'
    | '/_authenticated/workspace/assinatura'
    | '/_authenticated/workspace/atividades'
    | '/_authenticated/workspace/configuracoes'
    | '/_authenticated/workspace/creditos'
    | '/_authenticated/workspace/empresa'
    | '/_authenticated/workspace/equipe'
    | '/_authenticated/workspace/historico'
    | '/_authenticated/workspace/ia'
    | '/_authenticated/workspace/integracoes'
    | '/_authenticated/workspace/modulos'
    | '/_authenticated/workspace/notificacoes'
    | '/_authenticated/workspace/perfil'
    | '/_public/produtos/criador'
    | '/_public/produtos/planner'
    | '/_authenticated/configuracoes/'
    | '/_authenticated/planner/'
    | '/_authenticated/workspace/'
    | '/_authenticated/planner/projetos/$projectId'
    | '/_authenticated/planner/projetos/novo'
    | '/api/public/v1/openapi'
    | '/api/public/v1/ping'
    | '/api/public/v1/status'
    | '/api/public/v1/webhooks/mercadopago'
    | '/api/public/v1/workers/email'
    | '/api/public/v1/workers/render'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicV1OpenapiRoute: typeof ApiPublicV1OpenapiRoute
  ApiPublicV1PingRoute: typeof ApiPublicV1PingRoute
  ApiPublicV1StatusRoute: typeof ApiPublicV1StatusRoute
  ApiPublicV1WebhooksMercadopagoRoute: typeof ApiPublicV1WebhooksMercadopagoRoute
  ApiPublicV1WorkersEmailRoute: typeof ApiPublicV1WorkersEmailRoute
  ApiPublicV1WorkersRenderRoute: typeof ApiPublicV1WorkersRenderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/termos': {
      id: '/_public/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof PublicTermosRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/status': {
      id: '/_public/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof PublicStatusRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/sobre': {
      id: '/_public/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof PublicSobreRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/seguranca': {
      id: '/_public/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof PublicSegurancaRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/reembolso': {
      id: '/_public/reembolso'
      path: '/reembolso'
      fullPath: '/reembolso'
      preLoaderRoute: typeof PublicReembolsoRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/recursos': {
      id: '/_public/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof PublicRecursosRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/produtos': {
      id: '/_public/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof PublicProdutosRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacidade': {
      id: '/_public/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PublicPrivacidadeRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/planos': {
      id: '/_public/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PublicPlanosRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/integracoes': {
      id: '/_public/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof PublicIntegracoesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/faq': {
      id: '/_public/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PublicFaqRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/docs': {
      id: '/_public/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof PublicDocsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/cookies': {
      id: '/_public/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof PublicCookiesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contato': {
      id: '/_public/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof PublicContatoRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/changelog': {
      id: '/_public/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof PublicChangelogRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog': {
      id: '/_public/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof PublicBlogRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/storage': {
      id: '/_authenticated/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof AuthenticatedStorageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sites': {
      id: '/_authenticated/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AuthenticatedSitesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sistemas': {
      id: '/_authenticated/sistemas'
      path: '/sistemas'
      fullPath: '/sistemas'
      preLoaderRoute: typeof AuthenticatedSistemasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sdk': {
      id: '/_authenticated/sdk'
      path: '/sdk'
      fullPath: '/sdk'
      preLoaderRoute: typeof AuthenticatedSdkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recovery': {
      id: '/_authenticated/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof AuthenticatedRecoveryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quality': {
      id: '/_authenticated/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof AuthenticatedQualityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/observabilidade': {
      id: '/_authenticated/observabilidade'
      path: '/observabilidade'
      fullPath: '/observabilidade'
      preLoaderRoute: typeof AuthenticatedObservabilidadeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ia': {
      id: '/_authenticated/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof AuthenticatedIaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cicd': {
      id: '/_authenticated/cicd'
      path: '/cicd'
      fullPath: '/cicd'
      preLoaderRoute: typeof AuthenticatedCicdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cache': {
      id: '/_authenticated/cache'
      path: '/cache'
      fullPath: '/cache'
      preLoaderRoute: typeof AuthenticatedCacheRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/automacao': {
      id: '/_authenticated/automacao'
      path: '/automacao'
      fullPath: '/automacao'
      preLoaderRoute: typeof AuthenticatedAutomacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/api-gateway': {
      id: '/_authenticated/api-gateway'
      path: '/api-gateway'
      fullPath: '/api-gateway'
      preLoaderRoute: typeof AuthenticatedApiGatewayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspace/': {
      id: '/_authenticated/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof AuthenticatedWorkspaceIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/planner/': {
      id: '/_authenticated/planner/'
      path: '/'
      fullPath: '/planner/'
      preLoaderRoute: typeof AuthenticatedPlannerIndexRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/configuracoes/': {
      id: '/_authenticated/configuracoes/'
      path: '/configuracoes'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof AuthenticatedConfiguracoesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/produtos/planner': {
      id: '/_public/produtos/planner'
      path: '/planner'
      fullPath: '/produtos/planner'
      preLoaderRoute: typeof PublicProdutosPlannerRouteImport
      parentRoute: typeof PublicProdutosRoute
    }
    '/_public/produtos/criador': {
      id: '/_public/produtos/criador'
      path: '/criador'
      fullPath: '/produtos/criador'
      preLoaderRoute: typeof PublicProdutosCriadorRouteImport
      parentRoute: typeof PublicProdutosRoute
    }
    '/_authenticated/workspace/perfil': {
      id: '/_authenticated/workspace/perfil'
      path: '/perfil'
      fullPath: '/workspace/perfil'
      preLoaderRoute: typeof AuthenticatedWorkspacePerfilRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/notificacoes': {
      id: '/_authenticated/workspace/notificacoes'
      path: '/notificacoes'
      fullPath: '/workspace/notificacoes'
      preLoaderRoute: typeof AuthenticatedWorkspaceNotificacoesRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/modulos': {
      id: '/_authenticated/workspace/modulos'
      path: '/modulos'
      fullPath: '/workspace/modulos'
      preLoaderRoute: typeof AuthenticatedWorkspaceModulosRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/integracoes': {
      id: '/_authenticated/workspace/integracoes'
      path: '/integracoes'
      fullPath: '/workspace/integracoes'
      preLoaderRoute: typeof AuthenticatedWorkspaceIntegracoesRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/ia': {
      id: '/_authenticated/workspace/ia'
      path: '/ia'
      fullPath: '/workspace/ia'
      preLoaderRoute: typeof AuthenticatedWorkspaceIaRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/historico': {
      id: '/_authenticated/workspace/historico'
      path: '/historico'
      fullPath: '/workspace/historico'
      preLoaderRoute: typeof AuthenticatedWorkspaceHistoricoRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/equipe': {
      id: '/_authenticated/workspace/equipe'
      path: '/equipe'
      fullPath: '/workspace/equipe'
      preLoaderRoute: typeof AuthenticatedWorkspaceEquipeRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/empresa': {
      id: '/_authenticated/workspace/empresa'
      path: '/empresa'
      fullPath: '/workspace/empresa'
      preLoaderRoute: typeof AuthenticatedWorkspaceEmpresaRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/creditos': {
      id: '/_authenticated/workspace/creditos'
      path: '/creditos'
      fullPath: '/workspace/creditos'
      preLoaderRoute: typeof AuthenticatedWorkspaceCreditosRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/configuracoes': {
      id: '/_authenticated/workspace/configuracoes'
      path: '/configuracoes'
      fullPath: '/workspace/configuracoes'
      preLoaderRoute: typeof AuthenticatedWorkspaceConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/atividades': {
      id: '/_authenticated/workspace/atividades'
      path: '/atividades'
      fullPath: '/workspace/atividades'
      preLoaderRoute: typeof AuthenticatedWorkspaceAtividadesRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/assinatura': {
      id: '/_authenticated/workspace/assinatura'
      path: '/assinatura'
      fullPath: '/workspace/assinatura'
      preLoaderRoute: typeof AuthenticatedWorkspaceAssinaturaRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/assets': {
      id: '/_authenticated/workspace/assets'
      path: '/assets'
      fullPath: '/workspace/assets'
      preLoaderRoute: typeof AuthenticatedWorkspaceAssetsRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/api-keys': {
      id: '/_authenticated/workspace/api-keys'
      path: '/api-keys'
      fullPath: '/workspace/api-keys'
      preLoaderRoute: typeof AuthenticatedWorkspaceApiKeysRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/ajuda': {
      id: '/_authenticated/workspace/ajuda'
      path: '/ajuda'
      fullPath: '/workspace/ajuda'
      preLoaderRoute: typeof AuthenticatedWorkspaceAjudaRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/planner/visao': {
      id: '/_authenticated/planner/visao'
      path: '/visao'
      fullPath: '/planner/visao'
      preLoaderRoute: typeof AuthenticatedPlannerVisaoRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/planner/video': {
      id: '/_authenticated/planner/video'
      path: '/video'
      fullPath: '/planner/video'
      preLoaderRoute: typeof AuthenticatedPlannerVideoRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/planner/render': {
      id: '/_authenticated/planner/render'
      path: '/render'
      fullPath: '/planner/render'
      preLoaderRoute: typeof AuthenticatedPlannerRenderRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/planner/projetos': {
      id: '/_authenticated/planner/projetos'
      path: '/projetos'
      fullPath: '/planner/projetos'
      preLoaderRoute: typeof AuthenticatedPlannerProjetosRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/planner/producao': {
      id: '/_authenticated/planner/producao'
      path: '/producao'
      fullPath: '/planner/producao'
      preLoaderRoute: typeof AuthenticatedPlannerProducaoRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/planner/orcamentos': {
      id: '/_authenticated/planner/orcamentos'
      path: '/orcamentos'
      fullPath: '/planner/orcamentos'
      preLoaderRoute: typeof AuthenticatedPlannerOrcamentosRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/planner/materiais': {
      id: '/_authenticated/planner/materiais'
      path: '/materiais'
      fullPath: '/planner/materiais'
      preLoaderRoute: typeof AuthenticatedPlannerMateriaisRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/planner/marketplace': {
      id: '/_authenticated/planner/marketplace'
      path: '/marketplace'
      fullPath: '/planner/marketplace'
      preLoaderRoute: typeof AuthenticatedPlannerMarketplaceRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/planner/ia-studio': {
      id: '/_authenticated/planner/ia-studio'
      path: '/ia-studio'
      fullPath: '/planner/ia-studio'
      preLoaderRoute: typeof AuthenticatedPlannerIaStudioRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/planner/ia': {
      id: '/_authenticated/planner/ia'
      path: '/ia'
      fullPath: '/planner/ia'
      preLoaderRoute: typeof AuthenticatedPlannerIaRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/planner/engenharia': {
      id: '/_authenticated/planner/engenharia'
      path: '/engenharia'
      fullPath: '/planner/engenharia'
      preLoaderRoute: typeof AuthenticatedPlannerEngenhariaRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/planner/decoradora': {
      id: '/_authenticated/planner/decoradora'
      path: '/decoradora'
      fullPath: '/planner/decoradora'
      preLoaderRoute: typeof AuthenticatedPlannerDecoradoraRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/planner/configurador': {
      id: '/_authenticated/planner/configurador'
      path: '/configurador'
      fullPath: '/planner/configurador'
      preLoaderRoute: typeof AuthenticatedPlannerConfiguradorRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/planner/biblioteca': {
      id: '/_authenticated/planner/biblioteca'
      path: '/biblioteca'
      fullPath: '/planner/biblioteca'
      preLoaderRoute: typeof AuthenticatedPlannerBibliotecaRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/planner/assets': {
      id: '/_authenticated/planner/assets'
      path: '/assets'
      fullPath: '/planner/assets'
      preLoaderRoute: typeof AuthenticatedPlannerAssetsRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/configuracoes/empresa': {
      id: '/_authenticated/configuracoes/empresa'
      path: '/configuracoes/empresa'
      fullPath: '/configuracoes/empresa'
      preLoaderRoute: typeof AuthenticatedConfiguracoesEmpresaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/observabilidade': {
      id: '/_authenticated/admin/observabilidade'
      path: '/observabilidade'
      fullPath: '/admin/observabilidade'
      preLoaderRoute: typeof AuthenticatedAdminObservabilidadeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/billing': {
      id: '/_authenticated/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AuthenticatedAdminBillingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/biblioteca': {
      id: '/_authenticated/admin/biblioteca'
      path: '/biblioteca'
      fullPath: '/admin/biblioteca'
      preLoaderRoute: typeof AuthenticatedAdminBibliotecaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/v1/status': {
      id: '/api/public/v1/status'
      path: '/api/public/v1/status'
      fullPath: '/api/public/v1/status'
      preLoaderRoute: typeof ApiPublicV1StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/ping': {
      id: '/api/public/v1/ping'
      path: '/api/public/v1/ping'
      fullPath: '/api/public/v1/ping'
      preLoaderRoute: typeof ApiPublicV1PingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/openapi': {
      id: '/api/public/v1/openapi'
      path: '/api/public/v1/openapi'
      fullPath: '/api/public/v1/openapi'
      preLoaderRoute: typeof ApiPublicV1OpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/planner/projetos/novo': {
      id: '/_authenticated/planner/projetos/novo'
      path: '/novo'
      fullPath: '/planner/projetos/novo'
      preLoaderRoute: typeof AuthenticatedPlannerProjetosNovoRouteImport
      parentRoute: typeof AuthenticatedPlannerProjetosRoute
    }
    '/_authenticated/planner/projetos/$projectId': {
      id: '/_authenticated/planner/projetos/$projectId'
      path: '/$projectId'
      fullPath: '/planner/projetos/$projectId'
      preLoaderRoute: typeof AuthenticatedPlannerProjetosProjectIdRouteImport
      parentRoute: typeof AuthenticatedPlannerProjetosRoute
    }
    '/api/public/v1/workers/render': {
      id: '/api/public/v1/workers/render'
      path: '/api/public/v1/workers/render'
      fullPath: '/api/public/v1/workers/render'
      preLoaderRoute: typeof ApiPublicV1WorkersRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/workers/email': {
      id: '/api/public/v1/workers/email'
      path: '/api/public/v1/workers/email'
      fullPath: '/api/public/v1/workers/email'
      preLoaderRoute: typeof ApiPublicV1WorkersEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/webhooks/mercadopago': {
      id: '/api/public/v1/webhooks/mercadopago'
      path: '/api/public/v1/webhooks/mercadopago'
      fullPath: '/api/public/v1/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicV1WebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBibliotecaRoute: typeof AuthenticatedAdminBibliotecaRoute
  AuthenticatedAdminBillingRoute: typeof AuthenticatedAdminBillingRoute
  AuthenticatedAdminObservabilidadeRoute: typeof AuthenticatedAdminObservabilidadeRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBibliotecaRoute: AuthenticatedAdminBibliotecaRoute,
  AuthenticatedAdminBillingRoute: AuthenticatedAdminBillingRoute,
  AuthenticatedAdminObservabilidadeRoute:
    AuthenticatedAdminObservabilidadeRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedPlannerProjetosRouteChildren {
  AuthenticatedPlannerProjetosProjectIdRoute: typeof AuthenticatedPlannerProjetosProjectIdRoute
  AuthenticatedPlannerProjetosNovoRoute: typeof AuthenticatedPlannerProjetosNovoRoute
}

const AuthenticatedPlannerProjetosRouteChildren: AuthenticatedPlannerProjetosRouteChildren =
  {
    AuthenticatedPlannerProjetosProjectIdRoute:
      AuthenticatedPlannerProjetosProjectIdRoute,
    AuthenticatedPlannerProjetosNovoRoute:
      AuthenticatedPlannerProjetosNovoRoute,
  }

const AuthenticatedPlannerProjetosRouteWithChildren =
  AuthenticatedPlannerProjetosRoute._addFileChildren(
    AuthenticatedPlannerProjetosRouteChildren,
  )

interface AuthenticatedPlannerRouteChildren {
  AuthenticatedPlannerAssetsRoute: typeof AuthenticatedPlannerAssetsRoute
  AuthenticatedPlannerBibliotecaRoute: typeof AuthenticatedPlannerBibliotecaRoute
  AuthenticatedPlannerConfiguradorRoute: typeof AuthenticatedPlannerConfiguradorRoute
  AuthenticatedPlannerDecoradoraRoute: typeof AuthenticatedPlannerDecoradoraRoute
  AuthenticatedPlannerEngenhariaRoute: typeof AuthenticatedPlannerEngenhariaRoute
  AuthenticatedPlannerIaRoute: typeof AuthenticatedPlannerIaRoute
  AuthenticatedPlannerIaStudioRoute: typeof AuthenticatedPlannerIaStudioRoute
  AuthenticatedPlannerMarketplaceRoute: typeof AuthenticatedPlannerMarketplaceRoute
  AuthenticatedPlannerMateriaisRoute: typeof AuthenticatedPlannerMateriaisRoute
  AuthenticatedPlannerOrcamentosRoute: typeof AuthenticatedPlannerOrcamentosRoute
  AuthenticatedPlannerProducaoRoute: typeof AuthenticatedPlannerProducaoRoute
  AuthenticatedPlannerProjetosRoute: typeof AuthenticatedPlannerProjetosRouteWithChildren
  AuthenticatedPlannerRenderRoute: typeof AuthenticatedPlannerRenderRoute
  AuthenticatedPlannerVideoRoute: typeof AuthenticatedPlannerVideoRoute
  AuthenticatedPlannerVisaoRoute: typeof AuthenticatedPlannerVisaoRoute
  AuthenticatedPlannerIndexRoute: typeof AuthenticatedPlannerIndexRoute
}

const AuthenticatedPlannerRouteChildren: AuthenticatedPlannerRouteChildren = {
  AuthenticatedPlannerAssetsRoute: AuthenticatedPlannerAssetsRoute,
  AuthenticatedPlannerBibliotecaRoute: AuthenticatedPlannerBibliotecaRoute,
  AuthenticatedPlannerConfiguradorRoute: AuthenticatedPlannerConfiguradorRoute,
  AuthenticatedPlannerDecoradoraRoute: AuthenticatedPlannerDecoradoraRoute,
  AuthenticatedPlannerEngenhariaRoute: AuthenticatedPlannerEngenhariaRoute,
  AuthenticatedPlannerIaRoute: AuthenticatedPlannerIaRoute,
  AuthenticatedPlannerIaStudioRoute: AuthenticatedPlannerIaStudioRoute,
  AuthenticatedPlannerMarketplaceRoute: AuthenticatedPlannerMarketplaceRoute,
  AuthenticatedPlannerMateriaisRoute: AuthenticatedPlannerMateriaisRoute,
  AuthenticatedPlannerOrcamentosRoute: AuthenticatedPlannerOrcamentosRoute,
  AuthenticatedPlannerProducaoRoute: AuthenticatedPlannerProducaoRoute,
  AuthenticatedPlannerProjetosRoute:
    AuthenticatedPlannerProjetosRouteWithChildren,
  AuthenticatedPlannerRenderRoute: AuthenticatedPlannerRenderRoute,
  AuthenticatedPlannerVideoRoute: AuthenticatedPlannerVideoRoute,
  AuthenticatedPlannerVisaoRoute: AuthenticatedPlannerVisaoRoute,
  AuthenticatedPlannerIndexRoute: AuthenticatedPlannerIndexRoute,
}

const AuthenticatedPlannerRouteWithChildren =
  AuthenticatedPlannerRoute._addFileChildren(AuthenticatedPlannerRouteChildren)

interface AuthenticatedWorkspaceRouteChildren {
  AuthenticatedWorkspaceAjudaRoute: typeof AuthenticatedWorkspaceAjudaRoute
  AuthenticatedWorkspaceApiKeysRoute: typeof AuthenticatedWorkspaceApiKeysRoute
  AuthenticatedWorkspaceAssetsRoute: typeof AuthenticatedWorkspaceAssetsRoute
  AuthenticatedWorkspaceAssinaturaRoute: typeof AuthenticatedWorkspaceAssinaturaRoute
  AuthenticatedWorkspaceAtividadesRoute: typeof AuthenticatedWorkspaceAtividadesRoute
  AuthenticatedWorkspaceConfiguracoesRoute: typeof AuthenticatedWorkspaceConfiguracoesRoute
  AuthenticatedWorkspaceCreditosRoute: typeof AuthenticatedWorkspaceCreditosRoute
  AuthenticatedWorkspaceEmpresaRoute: typeof AuthenticatedWorkspaceEmpresaRoute
  AuthenticatedWorkspaceEquipeRoute: typeof AuthenticatedWorkspaceEquipeRoute
  AuthenticatedWorkspaceHistoricoRoute: typeof AuthenticatedWorkspaceHistoricoRoute
  AuthenticatedWorkspaceIaRoute: typeof AuthenticatedWorkspaceIaRoute
  AuthenticatedWorkspaceIntegracoesRoute: typeof AuthenticatedWorkspaceIntegracoesRoute
  AuthenticatedWorkspaceModulosRoute: typeof AuthenticatedWorkspaceModulosRoute
  AuthenticatedWorkspaceNotificacoesRoute: typeof AuthenticatedWorkspaceNotificacoesRoute
  AuthenticatedWorkspacePerfilRoute: typeof AuthenticatedWorkspacePerfilRoute
  AuthenticatedWorkspaceIndexRoute: typeof AuthenticatedWorkspaceIndexRoute
}

const AuthenticatedWorkspaceRouteChildren: AuthenticatedWorkspaceRouteChildren =
  {
    AuthenticatedWorkspaceAjudaRoute: AuthenticatedWorkspaceAjudaRoute,
    AuthenticatedWorkspaceApiKeysRoute: AuthenticatedWorkspaceApiKeysRoute,
    AuthenticatedWorkspaceAssetsRoute: AuthenticatedWorkspaceAssetsRoute,
    AuthenticatedWorkspaceAssinaturaRoute:
      AuthenticatedWorkspaceAssinaturaRoute,
    AuthenticatedWorkspaceAtividadesRoute:
      AuthenticatedWorkspaceAtividadesRoute,
    AuthenticatedWorkspaceConfiguracoesRoute:
      AuthenticatedWorkspaceConfiguracoesRoute,
    AuthenticatedWorkspaceCreditosRoute: AuthenticatedWorkspaceCreditosRoute,
    AuthenticatedWorkspaceEmpresaRoute: AuthenticatedWorkspaceEmpresaRoute,
    AuthenticatedWorkspaceEquipeRoute: AuthenticatedWorkspaceEquipeRoute,
    AuthenticatedWorkspaceHistoricoRoute: AuthenticatedWorkspaceHistoricoRoute,
    AuthenticatedWorkspaceIaRoute: AuthenticatedWorkspaceIaRoute,
    AuthenticatedWorkspaceIntegracoesRoute:
      AuthenticatedWorkspaceIntegracoesRoute,
    AuthenticatedWorkspaceModulosRoute: AuthenticatedWorkspaceModulosRoute,
    AuthenticatedWorkspaceNotificacoesRoute:
      AuthenticatedWorkspaceNotificacoesRoute,
    AuthenticatedWorkspacePerfilRoute: AuthenticatedWorkspacePerfilRoute,
    AuthenticatedWorkspaceIndexRoute: AuthenticatedWorkspaceIndexRoute,
  }

const AuthenticatedWorkspaceRouteWithChildren =
  AuthenticatedWorkspaceRoute._addFileChildren(
    AuthenticatedWorkspaceRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedApiGatewayRoute: typeof AuthenticatedApiGatewayRoute
  AuthenticatedAutomacaoRoute: typeof AuthenticatedAutomacaoRoute
  AuthenticatedCacheRoute: typeof AuthenticatedCacheRoute
  AuthenticatedCicdRoute: typeof AuthenticatedCicdRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedIaRoute: typeof AuthenticatedIaRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedObservabilidadeRoute: typeof AuthenticatedObservabilidadeRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRouteWithChildren
  AuthenticatedQualityRoute: typeof AuthenticatedQualityRoute
  AuthenticatedRecoveryRoute: typeof AuthenticatedRecoveryRoute
  AuthenticatedSdkRoute: typeof AuthenticatedSdkRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedSistemasRoute: typeof AuthenticatedSistemasRoute
  AuthenticatedSitesRoute: typeof AuthenticatedSitesRoute
  AuthenticatedStorageRoute: typeof AuthenticatedStorageRoute
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRouteWithChildren
  AuthenticatedConfiguracoesEmpresaRoute: typeof AuthenticatedConfiguracoesEmpresaRoute
  AuthenticatedConfiguracoesIndexRoute: typeof AuthenticatedConfiguracoesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedApiGatewayRoute: AuthenticatedApiGatewayRoute,
  AuthenticatedAutomacaoRoute: AuthenticatedAutomacaoRoute,
  AuthenticatedCacheRoute: AuthenticatedCacheRoute,
  AuthenticatedCicdRoute: AuthenticatedCicdRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedIaRoute: AuthenticatedIaRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedObservabilidadeRoute: AuthenticatedObservabilidadeRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRouteWithChildren,
  AuthenticatedQualityRoute: AuthenticatedQualityRoute,
  AuthenticatedRecoveryRoute: AuthenticatedRecoveryRoute,
  AuthenticatedSdkRoute: AuthenticatedSdkRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedSistemasRoute: AuthenticatedSistemasRoute,
  AuthenticatedSitesRoute: AuthenticatedSitesRoute,
  AuthenticatedStorageRoute: AuthenticatedStorageRoute,
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRouteWithChildren,
  AuthenticatedConfiguracoesEmpresaRoute:
    AuthenticatedConfiguracoesEmpresaRoute,
  AuthenticatedConfiguracoesIndexRoute: AuthenticatedConfiguracoesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicProdutosRouteChildren {
  PublicProdutosCriadorRoute: typeof PublicProdutosCriadorRoute
  PublicProdutosPlannerRoute: typeof PublicProdutosPlannerRoute
}

const PublicProdutosRouteChildren: PublicProdutosRouteChildren = {
  PublicProdutosCriadorRoute: PublicProdutosCriadorRoute,
  PublicProdutosPlannerRoute: PublicProdutosPlannerRoute,
}

const PublicProdutosRouteWithChildren = PublicProdutosRoute._addFileChildren(
  PublicProdutosRouteChildren,
)

interface PublicRouteChildren {
  PublicBlogRoute: typeof PublicBlogRoute
  PublicChangelogRoute: typeof PublicChangelogRoute
  PublicContatoRoute: typeof PublicContatoRoute
  PublicCookiesRoute: typeof PublicCookiesRoute
  PublicDocsRoute: typeof PublicDocsRoute
  PublicFaqRoute: typeof PublicFaqRoute
  PublicIntegracoesRoute: typeof PublicIntegracoesRoute
  PublicPlanosRoute: typeof PublicPlanosRoute
  PublicPrivacidadeRoute: typeof PublicPrivacidadeRoute
  PublicProdutosRoute: typeof PublicProdutosRouteWithChildren
  PublicRecursosRoute: typeof PublicRecursosRoute
  PublicReembolsoRoute: typeof PublicReembolsoRoute
  PublicSegurancaRoute: typeof PublicSegurancaRoute
  PublicSobreRoute: typeof PublicSobreRoute
  PublicStatusRoute: typeof PublicStatusRoute
  PublicTermosRoute: typeof PublicTermosRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicBlogRoute: PublicBlogRoute,
  PublicChangelogRoute: PublicChangelogRoute,
  PublicContatoRoute: PublicContatoRoute,
  PublicCookiesRoute: PublicCookiesRoute,
  PublicDocsRoute: PublicDocsRoute,
  PublicFaqRoute: PublicFaqRoute,
  PublicIntegracoesRoute: PublicIntegracoesRoute,
  PublicPlanosRoute: PublicPlanosRoute,
  PublicPrivacidadeRoute: PublicPrivacidadeRoute,
  PublicProdutosRoute: PublicProdutosRouteWithChildren,
  PublicRecursosRoute: PublicRecursosRoute,
  PublicReembolsoRoute: PublicReembolsoRoute,
  PublicSegurancaRoute: PublicSegurancaRoute,
  PublicSobreRoute: PublicSobreRoute,
  PublicStatusRoute: PublicStatusRoute,
  PublicTermosRoute: PublicTermosRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicV1OpenapiRoute: ApiPublicV1OpenapiRoute,
  ApiPublicV1PingRoute: ApiPublicV1PingRoute,
  ApiPublicV1StatusRoute: ApiPublicV1StatusRoute,
  ApiPublicV1WebhooksMercadopagoRoute: ApiPublicV1WebhooksMercadopagoRoute,
  ApiPublicV1WorkersEmailRoute: ApiPublicV1WorkersEmailRoute,
  ApiPublicV1WorkersRenderRoute: ApiPublicV1WorkersRenderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
