export const PLANNER_AGENTS = [
    {
        id: "designer",
        label: "Designer",
        order: 10,
        advisory: false,
        responsibilities: ["layout", "ergonomia", "circulação", "composição", "estilo", "estética"],
        allowedTools: [
            "create_room_preset",
            "layout_room",
            "set_style",
            "center",
            "rotate",
            "mirror",
            "panel_ripado",
            "check_circulation",
            "review_project",
        ],
        forbiddenTools: [
            "change_material",
            "change_color",
            "apply_finishing",
            "change_hardware",
            "resize",
            "toggle_led",
        ],
        keywords: [
            "layout",
            "ergonomia",
            "circulacao",
            "circulação",
            "estilo",
            "estetica",
            "estética",
            "composicao",
            "composição",
            "moderno",
            "minimalista",
            "classico",
            "clássico",
            "industrial",
            "luxo",
            "ambiente",
            "cozinha",
            "closet",
            "sala",
            "quarto",
            "dormitorio",
            "dormitório",
            "escritorio",
            "escritório",
            "banheiro",
            "painel",
        ],
        persona: "Designer de interiores sênior: cuida de layout, fluxo de circulação, ergonomia e proporção. Propõe composições agradáveis e coerentes com o estilo pedido.",
    },
    {
        id: "marceneiro",
        label: "Marceneiro",
        order: 20,
        advisory: false,
        responsibilities: ["módulos", "medidas", "ferragens", "estrutura", "montagem"],
        allowedTools: [
            "insert_item",
            "insert_described",
            "resize",
            "convert_to",
            "set_front_type",
            "change_hardware",
            "duplicate",
            "remove",
            "open_all",
        ],
        forbiddenTools: ["create_room_preset", "set_style", "change_material", "apply_finishing"],
        keywords: [
            "modulo",
            "módulo",
            "medida",
            "medidas",
            "largura",
            "altura",
            "profundidade",
            "ferragem",
            "ferragens",
            "dobradica",
            "dobradiça",
            "corredica",
            "corrediça",
            "puxador",
            "gaveta",
            "porta",
            "aereo",
            "aéreo",
            "balcao",
            "balcão",
            "torre",
            "gaveteiro",
            "nicho",
            "prateleira",
            "estrutura",
            "montagem",
            "roupeiro",
        ],
        persona: "Marceneiro sênior: define módulos reais, medidas de fabricação, frentes, ferragens e estrutura. Garante que tudo seja executável em fábrica.",
    },
    {
        id: "materiais",
        label: "Materiais",
        order: 30,
        advisory: false,
        responsibilities: ["MDF", "BP", "vidro", "alumínio", "cores", "acabamentos", "marcas"],
        allowedTools: ["search_material", "change_material", "change_color", "apply_finishing"],
        forbiddenTools: ["insert_item", "insert_described", "create_room_preset", "resize"],
        keywords: [
            "mdf",
            "mdp",
            "bp",
            "vidro",
            "aluminio",
            "alumínio",
            "cor",
            "cores",
            "acabamento",
            "acabamentos",
            "freijo",
            "freijó",
            "carvalho",
            "nogueira",
            "branco",
            "grafite",
            "textura",
            "duratex",
            "arauco",
            "guararapes",
            "berneck",
            "laca",
            "fosco",
            "brilho",
        ],
        persona: "Especialista em materiais: escolhe chapas, cores, texturas, vidros e acabamentos reais de catálogo, com marca e código coerentes.",
    },
    {
        id: "orcamentista",
        label: "Orçamentista",
        order: 40,
        advisory: true,
        responsibilities: ["custo", "materiais", "ferragens", "estimativas", "composição financeira"],
        allowedTools: ["estimate_budget"],
        forbiddenTools: [
            "insert_item",
            "insert_described",
            "create_room_preset",
            "change_material",
            "change_color",
            "apply_finishing",
            "resize",
        ],
        keywords: [
            "orcamento",
            "orçamento",
            "custo",
            "custos",
            "preco",
            "preço",
            "valor",
            "quanto custa",
            "estimativa",
            "investimento",
            "parcelamento",
            "margem",
            "financeiro",
        ],
        persona: "Orçamentista: estima custo de chapas, ferragens, serviços e margem. Nunca altera o projeto — apenas calcula e explica a composição financeira.",
    },
    {
        id: "producao",
        label: "Produção",
        order: 50,
        advisory: true,
        responsibilities: ["sequência de fabricação", "montagem", "corte", "prioridades", "logística"],
        allowedTools: ["production_summary", "preliminary_cut_list"],
        forbiddenTools: [
            "insert_item",
            "insert_described",
            "create_room_preset",
            "change_material",
            "apply_finishing",
        ],
        keywords: [
            "producao",
            "produção",
            "fabricacao",
            "fabricação",
            "corte",
            "plano de corte",
            "usinagem",
            "cnc",
            "sequencia",
            "sequência",
            "prazo",
            "logistica",
            "logística",
            "montagem",
            "etiqueta",
            "prioridade",
        ],
        persona: "Analista de produção: organiza sequência de fabricação, corte, usinagem, prioridades e logística de montagem. Não altera o desenho — orienta a execução.",
    },
    {
        id: "render",
        label: "Render",
        order: 60,
        advisory: false,
        responsibilities: ["câmera", "iluminação", "materiais visuais", "qualidade", "presets"],
        allowedTools: ["toggle_led", "set_render_preset", "set_camera"],
        forbiddenTools: ["insert_item", "create_room_preset", "resize", "change_material"],
        keywords: [
            "render",
            "renderizar",
            "camera",
            "câmera",
            "iluminacao",
            "iluminação",
            "luz",
            "led",
            "hdri",
            "foto",
            "fotorrealista",
            "preset",
            "qualidade",
            "8k",
            "4k",
            "spot",
            "pendente",
            "cena",
        ],
        persona: "Especialista em render: cuida de câmera, iluminação cênica, presets e qualidade visual da apresentação.",
    },
];
export const PLANNER_AGENT_BY_ID = Object.fromEntries(PLANNER_AGENTS.map((a) => [a.id, a]));
/** Índice inverso ferramenta → agente proprietário (ownership exclusivo). */
export const TOOL_OWNER = (() => {
    const map = {};
    for (const agent of PLANNER_AGENTS) {
        for (const tool of agent.allowedTools) {
            if (!map[tool])
                map[tool] = agent.id;
        }
    }
    return map;
})();
export function ownerOfTool(tool) {
    return TOOL_OWNER[tool] ?? "marceneiro";
}
export function agentCanRun(agent, tool) {
    const def = PLANNER_AGENT_BY_ID[agent];
    if (!def)
        return false;
    if (def.forbiddenTools.includes(tool))
        return false;
    return def.allowedTools.includes(tool);
}
